### ISSUE TITLE
Implicits conversions resolution

### ISSUE THREAD

**Issue by lopezavila69** [deanwampler/prog-scala-2nd-ed-code-examples#15]
Hello,

In the Implicits chapter it is detailed that: [...] "implicit methods are considered an optional feature as of Scala 2.10, so you should enable the feature explicitly with the import statement, 
`import scala.language.implicitConversions`, or with the global `-language:implicitConversions` compiler option.

Using the latest sources for Scala 2.11.7 I found that the import in the src files it is not working:

    scala> :load src/main/scala/progscala2/implicits/implicit-conversions-resolution.sc
    Loading src\main\scala\progscala2\implicits\implicit-conversions-resolution.sc...
    import scala.language.implicitConversions
    defined class Foo
    <console>:15: error: Foo.type does not take parameters
         implicit def fromString(s: String): Foo = Foo(s)
                                                      ^
    <console>:16: error: type mismatch;
     found   : String
     required: Foo
             def m(s: String) = m1(s)
                               ^

    scala> :load src/main/scala/progscala2/implicits/implicit-conversions-resolution2.sc
    Loading src\main\scala\progscala2\implicits\implicit-conversions-resolution2.sc...
    import scala.language.implicitConversions
    defined class Foo
    <console>:16: error: Foo.type does not take parameters
             implicit def fromString(s: String): Foo = Foo(s)
                                                      ^
        overridingConversion: (s: String)Foo
        defined class O

In case of adding the option to `build.sbt`file, should the global compiler option added here: `scalacOptions ++= Seq(...)`

Thanks,
Álvaro

**Comment by deanwampler** [comment]
The problem is that you can't just `:load` the script, unfortunately. The compiler needs to compile the `case class Foo` and the "reopened" `object Foo` together, but it doesn't do this automatically when you load a file. Instead, you have to use `:paste` mode and then copy and paste the code into the REPL. 

If you open the file in an editor, then just copy and paste into the REPL without `:paste` mode, you'll see this error. If you use `:paste` first, then it will compile successfully. I'll add a comment to the source file.

**Comment by lopezavila69** [comment]
Thank yoy very much, Dean. Certainly, that was the problem. Now it is possible to see the "Foo" strings once the 'm' method is invoked.
